name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  stale:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        repository:
          - cloudfoundry/bosh-agent-index
          - cloudfoundry/bosh-compiled-releases-index
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          repository: ${{ matrix.repository }}
      # GITHUB_REPOSITORY is protected and can not be set
      # change to GH_REPOSITORY instead
      - name: Patch stale resource to allow setting repository
        run: |
          sed -i 's/process.env.GITHUB_REPOSITORY/process.env.GH_REPOSITORY/g' \
            /home/runner/work/_actions/actions/stale/*/dist/index.js
        shell: bash
      - uses: actions/stale@v3
        env:
          GH_REPOSITORY: ${{ matrix.repository }}
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          stale-issue-message: 'This issue is stale because it has been open 21 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          stale-pr-message: 'This PR is stale because it has been open 21 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity. Feel free to re-open the issue if it was closed prematurely'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity. Feel free to re-open the PR if it was closed prematurely'
          days-before-issue-stale: 21
          days-before-pr-stale: 21
          days-before-issue-close: 7
          days-before-pr-close: 7
