name: 'Close stale issues and PRs'
on:
  push:
    paths:
      - 'repositories.list'
      - '.github/workflows/stale.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  provide_repositories_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: matrix
        run: |
          echo "::set-output name=matrix::$(jq -csR 'split("\n") | map(select(. != ""))' repositories.list)"
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}

  stale:
    needs: provide_repositories_json
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJson(needs.provide_repositories_json.outputs.matrix) }}

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          repository: ${{ matrix.repository }}
      # GITHUB_REPOSITORY is protected and can not be set
      # change to GH_REPOSITORY instead
      - name: Patch stale resource to allow setting repository
        run: |
          sed -i 's/process.env.GITHUB_REPOSITORY/process.env.GH_REPOSITORY/g' \
            /home/runner/work/_actions/actions/stale/*/dist/index.js
        shell: bash
      - uses: actions/stale@v3
        env:
          GH_REPOSITORY: ${{ matrix.repository }}
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          stale-issue-message: 'This issue was marked as `Stale` because it has been open for 21 days without any activity. If no activity takes place in the coming 7 days it will automatically be close. To prevent this from happening remove the `Stale` label or comment below.'
          stale-pr-message: 'This pull request was marked as `Stale` because it has been open for 21 days without any activity. If no activity takes place in the coming 7 days it will automatically be close. To prevent this from happening remove the `Stale` label or comment below.'
          close-issue-message: 'This issue was closed because it has been labeled `Stale` for 7 days without subsequent activity. Feel free to re-open this issue at any time by commenting below.'
          close-pr-message: 'This pull request was closed because it has been labeled `Stale` for 7 days without subsequent activity. Feel free to re-open this pull request at any time by commenting below.'
          days-before-issue-stale: 21
          days-before-pr-stale: 21
          days-before-issue-close: 7
          days-before-pr-close: 7
          debug-only: true
