name: 'Update repository list'
on:
  push:
    paths:
      - '.github/workflows/update-repository-list.yml'
      - 'bin/update-repository-list.sh'
      - 'bin/fi-working-group-repo-list.sh'
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_repositories:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2      
      - name: Update repository list
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pushd /tmp
          curl -OL https://github.com/cli/cli/releases/download/v2.6.0/gh_2.6.0_linux_amd64.tar.gz
          tar -xf gh_2.6.0_linux_amd64.tar.gz
          mv gh_2.6.0_linux_amd64/bin/gh /usr/local/bin
          curl -OL https://github.com/geofffranks/spruce/releases/download/v1.29.0/spruce-linux-amd64
          chmod +x spruce-linux-amd64
          mv spruce-linux-amd64 /usr/local/bin/spruce
          popd
          ./bin/update-repository-list.sh
          if [[ -n $(git status -s) ]]; then
            git config user.name bosh-admin-bot
            git config user.email dap-tas-journey-bosh-ecosystem@vmware.com
            git add .
            git commit -m "Update {vmware_,}repositories.list"
            git push
          fi

