name: 'Update repository list'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_repositories:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2      
      - name: Update repository list
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ./bin/update-repository-list.sh
          if [[ -n $(git status -s) ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update repositories.list"
            git push
          fi

