name: 'Update repository list'
on:
  push:
    paths:
      - '.github/workflows/update-repository-list.yml'
      - 'bin/update-repository-list.sh'
      - 'bin/fi-working-group-repo-list.sh'
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_repositories:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2      
      - name: Update repository list
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ./bin/update-repository-list.sh
          if [[ -n $(git status -s) ]]; then
            git config user.name bosh-admin-bot
            git config user.email dap-tas-journey-bosh-ecosystem@vmware.com
            git add .
            git commit -m "Update repositories.list"
            git push
          fi

